import React, { useState } from 'react';
import { useForm, Controller } from "react-hook-form";
import { useNavigate, useParams } from 'react-router';

import Option  from '../../components/Option/Option';
import Button from '../../components/Button/Button';
import InputText from '../../components/InputText/InputText';

import './Home.css';


const Home = () => {
    const navigate = useNavigate();

    const { register, handleSubmit, watch, control } = useForm({
        defaultValues: {
            'prompt': "",
            'resolution': "256x256"
        }
    });

    const onSubmit = data => {
        if(data){
            const{prompt, resolution} = data;
            navigate(`result/?prompt=${prompt}&resolution=${resolution}`);
        }
    }

    return (
        <div className="home">
            <div className="home__inner">
                <div className="home__content">
                    <div className="home__content__inner">
                        <div className="home__content__action">
                            <div className="home__content__action__inner">
                                <div className="home__content__action__text">
                                    <div className="home__content__action__text__inner">
                                        <div className="home__content__action__text__title">
                                            <div className="home__content__action__text__title__inner">
                                                <h1 className="heading heading_big">
                                                    InstaPix AI Art Generator
                                                </h1>
                                            </div>
                                        </div>
                                        <div className="home__content__action__text__description">
                                            <div className="home__content__action__text__description__inner">
                                                <p className="paragraph">
                                                    A web application that uses artificial intelligence to create original works of art. It can take input from users in the form of text or images and use it to generate original pieces of art in a variety of styles. The art generated by the AI can be used for various purposes such as wallpapers, social media posts, or even as the basis for further creative work.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="home__content__action__form">
                                    <div className="home__content__action__form__inner">
                                        <div className="home__content__action__form__label">
                                            <div className="home__content__action__form__label__inner">
                                                <div className="home__content__action__form__label__element">
                                                    <div>
                                                        Type what you want to see
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <form className="home__content__action__form__element" onSubmit={handleSubmit(onSubmit)}>
                                            <div className="home__content__action__form__element__inner">
                                                <div className="home__content__action__form__element__input">
                                                    <div className="home__content__action__form__element__input__inner">
                                                        <InputText
                                                            register={register}
                                                            name="prompt"
                                                            value={watch("prompt")}
                                                        />
                                                    </div>
                                                </div>
                                                 <div className="home__content__action__form__element__resolution">
                                                    <div className="home__content__action__form__element__submit__resolution__inner">
                                                        <Controller
                                                            control={control}
                                                            name="resolution"
                                                            render={ ({ field: {onChange, value} })=> (
                                                                <Option
                                                                    label="Choose resolution size"
                                                                    value={value}
                                                                    setValue={onChange}
                                                                    options={['256x256', '512x512', '1024x1024']}
                                                                />
                                                            ) }
                                                        />
                                                    </div>
                                                 </div>
                                                <div className="home__content__action__form__element__submit">
                                                    <div className="home__content__action__form__element__submit__inner">
                                                        <Button
                                                            variant='filled'
                                                            text='Generate Art'
                                                        />
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Home;