import React from 'react';
import { useForm } from "react-hook-form";
import InputText from '../../components/InputText/InputText';

import './Home.css';

const Home = () => {

    const { register, handleSubmit, watch } = useForm();

    const onCreate = data => {
        console.log(data)
    }

    return (
        <div className="home">
            <div className="home__inner">
                <div className="home__content">
                    <div className="home__content__inner">
                        <div className="home__content__action">
                            <div className="home__content__action__inner">
                                <div className="home__content__action__text">
                                    <div className="home__content__action__text__inner">
                                        <div className="home__content__action__text__title">
                                            <div className="home__content__action__text__title__inner">
                                                <h1 className="heading heading_big">
                                                    InstaPix AI Art Generator
                                                </h1>
                                            </div>
                                        </div>
                                        <div className="home__content__action__text__description">
                                            <div className="home__content__action__text__description__inner">
                                                <p className="paragraph">
                                                    A web application that uses artificial intelligence to create original works of art. It can take input from users in the form of text or images and use it to generate original pieces of art in a variety of styles. The art generated by the AI can be used for various purposes such as wallpapers, social media posts, or even as the basis for further creative work.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="home__content__action__form">
                                    <div className="home__content__action__form__inner">
                                        <div className="home__content__action__form__label">
                                            <div className="home__content__action__form__label__inner">
                                                <div className="home__content__action__form__label__element">
                                                    Type what you want to see
                                                </div>
                                            </div>
                                        </div>
                                        <form className="home__content__action__form__element" onSubmit={handleSubmit(onCreate)}>
                                            <div className="home__content__action__form__element__inner">
                                                <div className="home__content__action__form__element__input">
                                                    <div className="home__content__action__form__element__input__inner">
                                                        <InputText
                                                            register={register}
                                                            name="homepage-inputText"
                                                            value={watch("homepage-inputText")}
                                                        />
                                                    </div>
                                                </div> 
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Home;